channels:
  - conda-forge
dependencies:
  - appmode
  - beautifulsoup4
  - requests
  - numpy
  - pandas
  - ipywidgets
  - IPython
  - traitlets
  - scipy
  - matplotlib
  - pywavelets
  - statsmodels
  - seaborn
